apiVersion: apps/v1
kind: Deployment

metadata:
  name: node-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: node-frontend

  template:
    metadata:
      labels:
        app: node-frontend

    spec:
      containers:
      - name: node-frontend

        image: node-frontend:v1
        imagePullPolicy: Never

        ports:
        - containerPort: 3000

        env:
        - name: BACKEND_URL
          value: "http://backend-service:5000"